version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: proto-type-mqtt
    container_name: proto-type-mqtt
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
      - ./storage:/var/www/storage
    networks:
      - laravel

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./var/www:/var/www
  #   depends_on:
  #     - app
  #   networks:
  #     - laravel


networks:
  laravel:
    driver: bridge
